"""Add auth and payments tables

Revision ID: 98638425586e
Revises: c5b976dba445
Create Date: 2025-04-22 11:23:29.300579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98638425586e'
down_revision: Union[str, None] = 'c5b976dba445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('operators', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('operators', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('operators', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('operators', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('operators_email_key', 'operators', type_='unique')
    op.create_index(op.f('ix_operators_email'), 'operators', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_email'), table_name='operators')
    op.create_unique_constraint('operators_email_key', 'operators', ['email'])
    op.alter_column('operators', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('operators', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('operators', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('operators', 'updated_at')
    op.drop_column('operators', 'created_at')
    # ### end Alembic commands ###
